=== s-u-a/suaserv/etc/items.dtd
<!ELEMENT items (building*,research*,robot*,ship*,defence*)>

<!ELEMENT building (costs?,time?,production?,size?,dependencies?)>
<!ATTLIST building
	id ID #REQUIRED
>
<!ELEMENT research (costs?,time?,dependencies?)>
<!ATTLIST research
	id ID #REQUIRED
>
<!ELEMENT robot (costs?,time?,dependencies?)>
<!ATTLIST robot
	id ID #REQUIRED
>
<!ELEMENT ship (costs?,time?,dependencies?,capacity?,strength?,speed?,types?)>
<!ATTLIST ship
	id ID #REQUIRED
>
<!ELEMENT defence (costs?,time?,dependencies?,strength?)>
<!ATTLIST defence
	id ID #REQUIRED
>

<!ELEMENT costs ( carbon?,aluminium?,wolfram?,radium? )>
<!ELEMENT production ( carbon?,aluminium?,wolfram?,radium?,tritium?,power? )>
<!ELEMENT size ( #PCDATA )>
<!ELEMENT time ( #PCDATA )>
<!ELEMENT dependencies ( dependency* )>
<!ELEMENT capacity ( ressources,robots )>
<!ELEMENT strength ( attack?,defence? )>
<!ELEMENT speed ( #PCDATA )>
<!ELEMENT types ( colonisation?, gathering?, attack?, transport?, espionage?, stationing? )>

<!ELEMENT carbon ( #PCDATA )>
<!ELEMENT aluminium ( #PCDATA )>
<!ELEMENT wolfram ( #PCDATA )>
<!ELEMENT radium ( #PCDATA )>
<!ELEMENT tritium ( #PCDATA )>
<!ELEMENT power ( #PCDATA )>

<!ELEMENT dependency EMPTY>
<!ATTLIST dependency
	id IDREF #REQUIRED
	level CDATA #REQUIRED
>

<!ELEMENT ressources ( #PCDATA )>
<!ELEMENT robots ( #PCDATA )>

<!ELEMENT attack ( #PCDATA )>
<!ELEMENT defence ( #PCDATA )>

<!ELEMENT colonisation EMPTY>
<!ELEMENT gathering EMPTY>
<!ELEMENT attack EMPTY>
<!ELEMENT transport EMPTY>
<!ELEMENT espionage EMPTY>
<!ELEMENT stationing EMPTY>

=== s-u-a/suaserv/etc/items.xml
<?xml version="1.0"?>
<!DOCTYPE items SYSTEM "items.dtd">
<items>
	<building id="B0">
		<costs>
			<carbon>40</carbon>
			<aluminium>15</aluminium>
			<wolfram>0</wolfram>
			<radium>0</radium>
		</costs>
		<time>145</time>
		<production>
			<carbon>40</carbon>
			<aluminium>0</aluminium>
			<wolfram>0</wolfram>
			<radium>0</radium>
			<tritium>0</tritium>
			<power>-5</power>
		</production>
	</building>
	<building id="B1">
		<costs>
			<carbon>63</carbon>
			<aluminium>20</aluminium>
			<wolfram>0</wolfram>
			<radium>0</radium>
		</costs>
		<time>205</time>
		<production>
			<carbon>0</carbon>
			<aluminium>26</aluminium>
			<wolfram>0</wolfram>
			<radium>0</radium>
			<tritium>0</tritium>
			<power>-7</power>
		</production>
	</building>
	<building id="B2">
		<costs>
			<carbon>120</carbon>
			<aluminium>50</aluminium>
			<wolfram>0</wolfram>
			<radium>0</radium>
		</costs>
		<time>358</time>
		<dependencies>
			<dependency id="B0" level="3" />
			<dependency id="B1" level="2" />
		</dependencies>
		<production>
			<carbon>0</carbon>
			<aluminium>0</aluminium>
			<wolfram>16</wolfram>
			<radium>0</radium>
			<tritium>0</tritium>
			<power>-10</power>
		</production>
	</building>
	<building id="B3">
		<costs>
			<carbon>250</carbon>
			<aluminium>130</aluminium>
			<wolfram>0</wolfram>
			<radium>0</radium>
		</costs>
		<time>468</time>
		<dependencies>
			<dependency id="B0" level="6" />
			<dependency id="B1" level="5" />
			<dependency id="B2" level="3" />
		</dependencies>
		<production>
			<carbon>0</carbon>
			<aluminium>0</aluminium>
			<wolfram>0</wolfram>
			<radium>5</radium>
			<tritium>0</tritium>
			<power>-40</power>
		</production>
	</building>
	<building id="B4">
		<costs>
			<carbon>300</carbon>
			<aluminium>170</aluminium>
			<wolfram>120</wolfram>
			<radium>0</radium>
		</costs>
		<time>605</time>
		<dependencies>
			<dependency id="B2" level="1" />
			<dependency id="F0" level="1" />
		</dependencies>
		<production>
			<carbon>0</carbon>
			<aluminium>0</aluminium>
			<wolfram>0</wolfram>
			<radium>0</radium>
			<tritium>4</tritium>
			<power>-35</power>
		</production>
	</building>
	<building id="B5">
		<costs>
			<carbon>150</carbon>
			<aluminium>70</aluminium>
			<wolfram>0</wolfram>
			<radium>0</radium>
		</costs>
		<time>155</time>
		<production>
			<carbon>0</carbon>
			<aluminium>0</aluminium>
			<wolfram>0</wolfram>
			<radium>0</radium>
			<tritium>0</tritium>
			<power>62</power>
		</production>
	</building>
	<building id="B6">
		<costs>
			<carbon>1000</carbon>
			<aluminium>500</aluminium>
			<wolfram>300</wolfram>
			<radium>0</radium>
		</costs>
		<time>1340</time>
		<dependencies>
			<dependency id="F3" level="3" />
		</dependencies>
		<production>
			<carbon>0</carbon>
			<aluminium>0</aluminium>
			<wolfram>0</wolfram>
			<radium>0</radium>
			<tritium>0</tritium>
			<power>97</power>
		</production>
	</building>
	<building id="B7">
		<costs>
			<carbon>5000000</carbon>
			<aluminium>5000000</aluminium>
			<wolfram>5000000</wolfram>
			<radium>5000000</radium>
		</costs>
		<time>542230</time>
		<dependencies>
			<dependency id="B2" level="30" />
			<dependency id="F3" level="15" />
			<dependency id="F9" level="1" />
		</dependencies>
		<production>
			<carbon>0</carbon>
			<aluminium>60000</aluminium>
			<wolfram>40000</wolfram>
			<radium>15000</radium>
			<tritium>0</tritium>
			<power>10000</power>
		</production>
	</building>
	<building id="B8">
		<costs>
			<carbon>100</carbon>
			<aluminium>80</aluminium>
			<wolfram>60</wolfram>
			<radium>50</radium>
		</costs>
		<time>745</time>
		<dependencies>
			<dependency id="B2" level="5" />
			<dependency id="B3" level="2" />
		</dependencies>
		<production>
			<carbon>0</carbon>
			<aluminium>0</aluminium>
			<wolfram>0</wolfram>
			<radium>0</radium>
			<tritium>0</tritium>
			<power>0</power>
		</production>
	</building>
	<building id="B9">
		<costs>
			<carbon>60</carbon>
			<aluminium>50</aluminium>
			<wolfram>20</wolfram>
			<radium>10</radium>
		</costs>
		<time>625</time>
		<dependencies>
			<dependency id="B8" level="2" />
		</dependencies>
		<production>
			<carbon>0</carbon>
			<aluminium>0</aluminium>
			<wolfram>0</wolfram>
			<radium>0</radium>
			<tritium>0</tritium>
			<power>0</power>
		</production>
	</building>
	<building id="B10">
		<costs>
			<carbon>80</carbon>
			<aluminium>70</aluminium>
			<wolfram>60</wolfram>
			<radium>20</radium>
		</costs>
		<time>863</time>
		<dependencies>
			<dependency id="B4" level="2" />
			<dependency id="F0" level="1" />
			<dependency id="F6" level="1" />
		</dependencies>
		<production>
			<carbon>0</carbon>
			<aluminium>0</aluminium>
			<wolfram>0</wolfram>
			<radium>0</radium>
			<tritium>0</tritium>
			<power>0</power>
		</production>
	</building>

	<research id="F0">
		<costs>
			<carbon>600</carbon>
			<aluminium>500</aluminium>
			<wolfram>0</wolfram>
			<radium>100</radium>
		</costs>
		<time>665</time>
		<dependencies>
			<dependency id="B8" level="1" />
		</dependencies>
	</research>
	<research id="F1">
		<costs>
			<carbon>1250</carbon>
			<aluminium>1000</aluminium>
			<wolfram>500</wolfram>
			<radium>333</radium>
		</costs>
		<time>1133</time>
		<dependencies>
			<dependency id="B8" level="1" />
			<dependency id="B10" level="2" />
			<dependency id="F0" level="1" />
		</dependencies>
	</research>
	<research id="F2">
		<costs>
			<carbon>2000</carbon>
			<aluminium>1000</aluminium>
			<wolfram>120</wolfram>
			<radium>55</radium>
		</costs>
		<time>545</time>
		<dependencies>
			<dependency id="B8" level="2" />
			<dependency id="B9" level="1" />
		</dependencies>
	</research>
	<research id="F3">
		<costs>
			<carbon>1000</carbon>
			<aluminium>500</aluminium>
			<wolfram>350</wolfram>
			<radium>0</radium>
		</costs>
		<time>320</time>
		<dependencies>
			<dependency id="B5" level="3" />
			<dependency id="B8" level="2" />
		</dependencies>
	</research>
	<research id="F4">
		<costs>
			<carbon>2400</carbon>
			<aluminium>1255</aluminium>
			<wolfram>1000</wolfram>
			<radium>233</radium>
		</costs>
		<time>500</time>
		<dependencies>
			<dependency id="B8" level="2" />
			<dependency id="B10" level="3" />
			<dependency id="F0" level="2" />
		</dependencies>
	</research>
	<research id="F5">
		<costs>
			<carbon>2300</carbon>
			<aluminium>1144</aluminium>
			<wolfram>700</wolfram>
			<radium>300</radium>
		</costs>
		<time>513</time>
		<dependencies>
			<dependency id="B8" level="2" />
			<dependency id="B10" level="3" />
			<dependency id="F0" level="2" />
		</dependencies>
	</research>
	<research id="F10">
		<costs>
			<carbon>10000</carbon>
			<aluminium>5000</aluminium>
			<wolfram>2500</wolfram>
			<radium>3000</radium>
		</costs>
		<time>20733</time>
		<dependencies>
			<dependency id="B8" level="10" />
			<dependency id="B10" level="5" />
			<dependency id="F5" level="3" />
		</dependencies>
	</research>
	<research id="F6">
		<costs>
			<carbon>2000</carbon>
			<aluminium>1000</aluminium>
			<wolfram>500</wolfram>
			<radium>222</radium>
		</costs>
		<time>303</time>
		<dependencies>
			<dependency id="B8" level="3" />
			<dependency id="F3" level="2" />
		</dependencies>
	</research>
	<research id="F7">
		<costs>
			<carbon>10000</carbon>
			<aluminium>3333</aluminium>
			<wolfram>1000</wolfram>
			<radium>600</radium>
		</costs>
		<time>913</time>
		<dependencies>
			<dependency id="B8" level="7" />
			<dependency id="F3" level="5" />
		</dependencies>
	</research>
	<research id="F8">
		<costs>
			<carbon>1508549</carbon>
			<aluminium>1547298</aluminium>
			<wolfram>663875</wolfram>
			<radium>503226</radium>
		</costs>
		<time>172832</time>
		<dependencies>
			<dependency id="B8" level="20" />
			<dependency id="F3" level="12" />
		</dependencies>
	</research>
	<research id="F9">
		<costs>
			<carbon>415140368</carbon>
			<aluminium>247140344</aluminium>
			<wolfram>125590584</wolfram>
			<radium>81514736</radium>
		</costs>
		<time>604800</time>
		<dependencies>
			<dependency id="B8" level="30" />
			<dependency id="F2" level="20" />
		</dependencies>
	</research>
	<research id="F11">
		<costs>
			<carbon>200000</carbon>
			<aluminium>130000</aluminium>
			<wolfram>100000</wolfram>
			<radium>75000</radium>
		</costs>
		<time>24015</time>
		<dependencies>
			<dependency id="B8" level="20" />
			<dependency id="B10" level="15" />
			<dependency id="F0" level="5" />
			<dependency id="F2" level="6" />
		</dependencies>
	</research>

	<robot id="R01">
		<costs>
			<carbon>51893</carbon>
			<aluminium>43095</aluminium>
			<wolfram>32933</wolfram>
			<radium>19463</radium>
		</costs>
		<time>51365</time>
		<dependencies>
			<dependency id="B9" level="2" />
			<dependency id="F2" level="1" />
		</dependencies>
	</robot>
	<robot id="R02">
		<costs>
			<carbon>76329</carbon>
			<aluminium>58921</aluminium>
			<wolfram>49892</wolfram>
			<radium>28979</radium>
		</costs>
		<time>72985</time>
		<dependencies>
			<dependency id="B9" level="5" />
			<dependency id="F2" level="2" />
		</dependencies>
	</robot>
	<robot id="R03">
		<costs>
			<carbon>72984</carbon>
			<aluminium>75893</aluminium>
			<wolfram>53876</wolfram>
			<radium>30532</radium>
		</costs>
		<time>80493</time>
		<dependencies>
			<dependency id="B9" level="7" />
			<dependency id="F2" level="5" />
		</dependencies>
	</robot>
	<robot id="R04">
		<costs>
			<carbon>75823</carbon>
			<aluminium>65239</aluminium>
			<wolfram>73189</wolfram>
			<radium>34892</radium>
		</costs>
		<time>92893</time>
		<dependencies>
			<dependency id="B9" level="10" />
			<dependency id="F2" level="7" />
		</dependencies>
	</robot>
	<robot id="R05">
		<costs>
			<carbon>79894</carbon>
			<aluminium>69093</aluminium>
			<wolfram>58398</wolfram>
			<radium>55892</radium>
		</costs>
		<time>105842</time>
		<dependencies>
			<dependency id="B9" level="14" />
			<dependency id="F2" level="10" />
		</dependencies>
	</robot>
	<robot id="R06">
		<costs>
			<carbon>102985</carbon>
